version: '3'
services:

  app:
    build:
      context: ../src
      dockerfile: ../docker/php/Dockerfile
    container_name: lande-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    volumes:
      - ../src:/var/www
    networks:
      - test
  nginx:
    image: nginx:alpine
    container_name: lande-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../logs/nginx:/var/log/nginx
    networks:
      - test

networks:
  test:
    driver: bridge
